# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/adithirao/Documents/parallel/ezSIFT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/adithirao/Documents/parallel/ezSIFT/platforms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adithirao/Documents/parallel/ezSIFT/platforms/CMakeFiles /Users/adithirao/Documents/parallel/ezSIFT/platforms//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/adithirao/Documents/parallel/ezSIFT/platforms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ezsift

# Build rule for target.
ezsift: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ezsift
.PHONY : ezsift

# fast build rule for target.
ezsift/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/build
.PHONY : ezsift/fast

#=============================================================================
# Target rules for targets named feature_extract

# Build rule for target.
feature_extract: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 feature_extract
.PHONY : feature_extract

# fast build rule for target.
feature_extract/fast:
	$(MAKE) $(MAKESILENT) -f bin/examples/feature_extract/CMakeFiles/feature_extract.dir/build.make bin/examples/feature_extract/CMakeFiles/feature_extract.dir/build
.PHONY : feature_extract/fast

#=============================================================================
# Target rules for targets named image_match

# Build rule for target.
image_match: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_match
.PHONY : image_match

# fast build rule for target.
image_match/fast:
	$(MAKE) $(MAKESILENT) -f bin/examples/image_match/CMakeFiles/image_match.dir/build.make bin/examples/image_match/CMakeFiles/image_match.dir/build
.PHONY : image_match/fast

src/ezsift.o: src/ezsift.cpp.o

.PHONY : src/ezsift.o

# target to build an object file
src/ezsift.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/ezsift.cpp.o
.PHONY : src/ezsift.cpp.o

src/ezsift.i: src/ezsift.cpp.i

.PHONY : src/ezsift.i

# target to preprocess a source file
src/ezsift.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/ezsift.cpp.i
.PHONY : src/ezsift.cpp.i

src/ezsift.s: src/ezsift.cpp.s

.PHONY : src/ezsift.s

# target to generate assembly for a file
src/ezsift.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/ezsift.cpp.s
.PHONY : src/ezsift.cpp.s

src/image_utility.o: src/image_utility.cpp.o

.PHONY : src/image_utility.o

# target to build an object file
src/image_utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/image_utility.cpp.o
.PHONY : src/image_utility.cpp.o

src/image_utility.i: src/image_utility.cpp.i

.PHONY : src/image_utility.i

# target to preprocess a source file
src/image_utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/image_utility.cpp.i
.PHONY : src/image_utility.cpp.i

src/image_utility.s: src/image_utility.cpp.s

.PHONY : src/image_utility.s

# target to generate assembly for a file
src/image_utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/image_utility.cpp.s
.PHONY : src/image_utility.cpp.s

src/img-stitch.o: src/img-stitch.cpp.o

.PHONY : src/img-stitch.o

# target to build an object file
src/img-stitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/img-stitch.cpp.o
.PHONY : src/img-stitch.cpp.o

src/img-stitch.i: src/img-stitch.cpp.i

.PHONY : src/img-stitch.i

# target to preprocess a source file
src/img-stitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/img-stitch.cpp.i
.PHONY : src/img-stitch.cpp.i

src/img-stitch.s: src/img-stitch.cpp.s

.PHONY : src/img-stitch.s

# target to generate assembly for a file
src/img-stitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ezsift.dir/build.make CMakeFiles/ezsift.dir/src/img-stitch.cpp.s
.PHONY : src/img-stitch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ezsift"
	@echo "... feature_extract"
	@echo "... image_match"
	@echo "... src/ezsift.o"
	@echo "... src/ezsift.i"
	@echo "... src/ezsift.s"
	@echo "... src/image_utility.o"
	@echo "... src/image_utility.i"
	@echo "... src/image_utility.s"
	@echo "... src/img-stitch.o"
	@echo "... src/img-stitch.i"
	@echo "... src/img-stitch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

