# CMake generated Testfile for 
# Source directory: /Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn
# Build directory: /Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/modules/dnn
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_dnn "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/bin/opencv_test_dnn" "--gtest_output=xml:opencv_test_dnn.xml")
set_tests_properties(opencv_test_dnn PROPERTIES  LABELS "Main;opencv_dnn;Accuracy" WORKING_DIRECTORY "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVUtils.cmake;1707;add_test;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVModule.cmake;1315;ocv_add_test_from_target;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;168;ocv_add_accuracy_tests;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_perf_dnn "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml")
set_tests_properties(opencv_perf_dnn PROPERTIES  LABELS "Main;opencv_dnn;Performance" WORKING_DIRECTORY "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/test-reports/performance" _BACKTRACE_TRIPLES "/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVUtils.cmake;1707;add_test;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVModule.cmake;1217;ocv_add_test_from_target;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;173;ocv_add_perf_tests;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;0;")
add_test(opencv_sanity_dnn "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/bin/opencv_perf_dnn" "--gtest_output=xml:opencv_perf_dnn.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_dnn PROPERTIES  LABELS "Main;opencv_dnn;Sanity" WORKING_DIRECTORY "/Users/vmantha/Desktop/parallelImageStitcher/include/build_opencv/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVUtils.cmake;1707;add_test;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/cmake/OpenCVModule.cmake;1218;ocv_add_test_from_target;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;173;ocv_add_perf_tests;/Users/vmantha/Desktop/parallelImageStitcher/include/opencv/modules/dnn/CMakeLists.txt;0;")
